### ISSUE TITLE
Cannot compile on Swift 2.0/Xcode 7 beta 6

### ISSUE THREAD

**Issue by nicholaswyoung** [socketio/socket.io-client-swift#165]
First off, apologies for the long error trace. I hope this helps – it seems like there are quite a few errors when I try to compile on Yosemite / Swift 2.0.
```
Apple Swift version 2.0 (swiftlang-700.0.57.3 clang-700.0.72)
Target: x86_64-apple-darwin14.4.0
```
```
*** Fetching socket.io-client-swift
*** Checking out socket.io-client-swift at "17426c14320b485670e2e3e45c1fa2264b261177"
*** xcodebuild output can be found in /var/folders/v3/ywxzgjl56036gvb1zxy2cg680000gn/T/carthage-xcodebuild.wlrQzJ.log
*** Building scheme "SocketIO-Mac" in Socket.IO-Client-Swift.xcodeproj
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:120:23: error: '#' has been removed from Swift; double up 'fast fast' to make the argument label the same as the parameter name
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEventHandler.swift:41:26: warning: extraneous '_' in parameter: 'items' has no keyword argument name
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:158:23: error: '#' has been removed from Swift; double up 'fast fast' to make the argument label the same as the parameter name
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:178:25: error: '#' has been removed from Swift; double up 'timeoutAfter timeoutAfter' to make the argument label the same as the parameter name
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:271:28: error: '#' has been removed from Swift; double up 'fast fast' to make the argument label the same as the parameter name
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:92:33: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:140:17: warning: variable 'mutData' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:161:13: warning: variable 'url' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:265:50: error: value of optional type 'NSError?' not unwrapped; did you mean to use '!' or '?'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:267:42: error: value of optional type 'NSError?' not unwrapped; did you mean to use '!' or '?'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:274:45: error: value of optional type 'NSData?' not unwrapped; did you mean to use '!' or '?'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:319:23: error: cannot invoke 'count' with an argument list of type '(String)'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:349:46: error: value of optional type 'NSError?' not unwrapped; did you mean to use '!' or '?'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:352:27: error: value of optional type 'NSError?' not unwrapped; did you mean to use '!' or '?'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:387:22: error: 'advance' is unavailable: call the 'advancedBy(n)' method on the index
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:391:43: error: argument type 'dispatch_queue_attr_t!' does not conform to expected type 'dispatch_queue_t' (aka 'OS_dispatch_queue')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:400:35: error: argument type 'dispatch_queue_attr_t!' does not conform to expected type 'dispatch_queue_t' (aka 'OS_dispatch_queue')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:414:61: error: extra argument 'error' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:516:12: error: cannot invoke 'count' with an argument list of type '(String)'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:522:30: error: missing argument label 'arrayLiteral:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:536:28: error: cannot invoke 'count' with an argument list of type '(String)'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:570:35: error: argument type 'dispatch_queue_attr_t!' does not conform to expected type 'dispatch_queue_t' (aka 'OS_dispatch_queue')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:646:26: warning: immutable value 'nilData' was never used; consider replacing with '_' or removing it
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:667:32: warning: immutable value 'nilString' was never used; consider replacing with '_' or removing it
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEngine.swift:528:33: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:27:27: error: 'Printable' has been renamed to 'CustomStringConvertible'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:40:21: warning: variable 'newArr' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:48:21: warning: variable 'newDict' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:84:25: error: missing argument label 'arrayLiteral:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:106:34: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:144:20: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:148:78: error: cannot invoke 'count' with an argument list of type '(String)'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketParser.swift:163:71: error: extra argument 'error' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketTypes.swift:31:33: warning: '@objc_block' attribute is deprecated; '@convention(block)' should be used instead
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketEventHandler.swift:43:63: error: missing argument label 'num:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketAnyEvent.swift:27:20: error: only classes that inherit from NSObject can be declared @objc
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:125:32: error: cannot assign a value of type 'dispatch_queue_t' (aka 'OS_dispatch_queue') to a value of type 'dispatch_queue_attr_t!'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:127:32: error: cannot assign a value of type 'dispatch_queue_t!' to a value of type 'dispatch_queue_attr_t!'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:188:21: error: extraneous argument label 'opts:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:401:32: error: argument type 'dispatch_queue_attr_t!' does not conform to expected type 'dispatch_queue_t' (aka 'OS_dispatch_queue')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:409:40: error: argument type 'dispatch_queue_attr_t!' does not conform to expected type 'dispatch_queue_t' (aka 'OS_dispatch_queue')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:413:40: error: argument type 'dispatch_queue_attr_t!' does not conform to expected type 'dispatch_queue_t' (aka 'OS_dispatch_queue')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketIOClient.swift:448:29: error: cannot assign a value of type '[SocketEventHandler]' to a value of type 'ContiguousArray<SocketEventHandler>'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketLogger.swift:38:19: error: 'toString' has been renamed to 'String'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketLogger.swift:40:12: error: cannot invoke 'count' with an argument list of type '(String)'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketLogger.swift:41:28: error: 'advance' is unavailable: call the 'advancedBy(n)' method on the index
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:171:47: error: cannot force unwrap value of non-optional type 'String'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:187:53: warning: forced cast of 'String' to same type has no effect
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:187:76: warning: forced cast of 'String' to same type has no effect
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:194:76: error: 'join' is unavailable: call the 'joinWithSeparator()' method on the sequence of elements
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:198:82: error: cannot force unwrap value of non-optional type 'String'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:204:41: error: value of optional type 'Unmanaged<CFData>?' not unwrapped; did you mean to use '!' or '?'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:224:88: error: missing argument label 'rawValue:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:253:85: warning: forced cast from 'CFString' to 'String' always succeeds; did you mean to use 'as'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:254:86: warning: forced cast from 'CFString' to 'String' always succeeds; did you mean to use 'as'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:264:105: warning: forced cast of 'NSDate' to same type has no effect
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:271:98: warning: forced cast from 'CFString' to 'String' always succeeds; did you mean to use 'as'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:273:86: warning: forced cast from 'CFString' to 'String' always succeeds; did you mean to use 'as'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:271:17: warning: variable 'possibleTrust' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:273:21: warning: variable 'domain' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:317:13: warning: variable 'buffer' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:343:21: warning: variable 'combine' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:391:70: error: cannot convert value of type 'Int' to expected argument type 'Bool'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:407:13: warning: variable 'response' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:423:17: warning: variable 'offset' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:462:25: warning: variable 'codeBuffer' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:473:29: warning: variable 'str' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:609:40: warning: forced cast from 'NSString' to 'String' always succeeds; did you mean to use 'as'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:611:80: warning: forced cast from 'NSString' to 'String' always succeeds; did you mean to use 'as'?
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:602:21: warning: variable 'str' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:638:13: warning: variable 'buffer' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:673:21: warning: variable 'sizeBuffer' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:678:21: warning: variable 'sizeBuffer' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:683:17: warning: variable 'maskKey' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:697:21: warning: variable 'len' was never mutated; consider changing to 'let' constant
/Users/nicho** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
laswyoung/Code/machinefm/MachineFM/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:793:52: warning: forced cast of 'String' to same type has no effect
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:857:41: error: cannot convert value of type 'Int' to expected argument type 'Bool'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:859:22: error: value of type 'SecPolicy' has no member 'takeRetainedValue'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:882:32: error: value of type 'SecCertificate?' has no member 'takeRetainedValue'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:917:45: error: value of type 'SecCertificate' has no member 'takeRetainedValue'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:931:53: error: cannot convert value of type 'inout Unmanaged<SecTrust>?' (aka 'inout Optional<Unmanaged<SecTrust>>') to expected argument type 'UnsafeMutablePointer<SecTrust?>' (aka 'UnsafeMutablePointer<Optional<SecTrust>>')
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:936:20: error: value of type 'SecKey?' has no member 'takeRetainedValue'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:952:51: error: value of type 'SecCertificate?' has no member 'takeRetainedValue'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/WebSocket.swift:966:22: error: value of type 'SecPolicy' has no member 'takeRetainedValue'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:58:30: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:170:70: error: extra argument 'error' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:199:43: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:195:13: warning: variable 'newArr' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:211:38: error: 'toInt()' is unavailable: Use Int() initializer
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:216:17: warning: variable 'newDict' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketPacket.swift:224:17: warning: variable 'newArr' was never mutated; consider changing to 'let' constant
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:22:78: error: nil default argument value of cannot be converted to type 'NSRegularExpressionOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:28:28: error: cannot invoke initializer for type 'NSRegularExpression' with an argument list of type '(pattern: String, options: NSRegularExpressionOptions, error: inout NSError?)'
            if let regex = NSRegularExpression(pattern: pattern, options:options, error:&error) {
            if let regex = NSRegularExpression(pattern: pattern, options:options, error:&error) {
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:41:9: error: 'println' has been renamed to 'print'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:46:44: error: 'count' is unavailable: access the 'count' property on the collection
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:57:56: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:58:21: error: extraneous argument label 'options:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:61:52: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:62:75: error: nil is not compatible with expected argument type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:65:52: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:66:31: error: extraneous argument label 'options:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:69:53: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:110:52: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:112:13: warning: conditional cast from '[NSTextCheckingResult]' to '[NSTextCheckingResult]' always succeeds
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:121:53: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:122:28: error: extraneous argument label 'options:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:125:54: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:126:28: error: extraneous argument label 'options:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:129:56: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:130:28: error: extraneous argument label 'options:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:133:57: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:135:34: error: extraneous argument label 'options:' in call
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:142:37: error: nil default argument value of cannot be converted to type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:146:101: error: '(NSTextCheckingResult!, NSMatchingFlags, UnsafeMutablePointer<ObjCBool>) -> Void' is not convertible to '(NSTextCheckingResult?, NSMatchingFlags, UnsafeMutablePointer<ObjCBool>) -> Void'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:181:21: error: nil is not compatible with expected argument type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:194:21: error: nil is not compatible with expected argument type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:202:21: error: nil is not compatible with expected argument type 'NSMatchingOptions'
/Users/x/code/apps/websocket/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SwiftRegex.swift:208:21: error: nil is not compatible with expected argument type 'NSMatchingOptions'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by nuclearace** [comment]
You need to use the Swift 2 branch

**Comment by nuclearace** [comment]
Also, I have no idea how to get carthage to compile the Swift 2 branch.

**Comment by nicholaswyoung** [comment]
So far as I understand, xcode-select should setup the compiler correctly. Thanks for the quick response, @nuclearace – I'll jump to the Swift 2 branch and see how it goes!

**Comment by nicholaswyoung** [comment]
After upgrading Xcode to the latest Beta 6, I tried again to compile the ```swift-2``` branch. Still no luck. Carthage complains about the code signing certificate:

```
** BUILD FAILED **
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
A shell task failed with exit code 65:
** BUILD FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by nuclearace** [comment]
I'll have to look into this later, I know little about carthage building.

**Comment by nicholaswyoung** [comment]
@nuclearace Great. Thank you!

**Comment by nuclearace** [comment]
And if you really need too. You can add the swift files manually to your project.

**Comment by damionjn** [comment]
I believe this is a Carthage issue: https://github.com/Carthage/Carthage/issues/235
