### ISSUE TITLE
swift build doesn't build the project

### ISSUE THREAD

**Issue by MihaelIsaev** [socketio/socket.io-client-swift#781]
Hello

I've just tried to build the project from `swift4` branch and have no luck.. `swift build` stops with `CZLib not found` error 👎 

Could you please fix it?

**Comment by nuclearace** [comment]
Beta versions aren't supported officially, so there's no guarantee it will work or build. The swift4 branch is just around for testing.

**Comment by nuclearace** [comment]
But I'll look into it when I get a chance.

**Comment by MihaelIsaev** [comment]
Actually the same error with `master` branch

    Mikes-Macbook-Pro:socket.io-client-swift-master mihael$ swift build
    Fetching https://github.com/nuclearace/Starscream
    Fetching https://github.com/daltoniam/zlib-spm.git
    Fetching https://github.com/daltoniam/common-crypto-spm
    Fetching https://github.com/IBM-Swift/CommonCrypto.git
    Cloning https://github.com/daltoniam/zlib-spm.git
    Resolving https://github.com/daltoniam/zlib-spm.git at 1.1.0
    Cloning https://github.com/nuclearace/Starscream
    Resolving https://github.com/nuclearace/Starscream at 8.0.2
    Cloning https://github.com/IBM-Swift/CommonCrypto.git
    Resolving https://github.com/IBM-Swift/CommonCrypto.git at 0.1.4
    Compile Swift Module 'StarscreamSocketIO' (3 sources)
    /Users/mihael/Downloads/socket.io-client-swift-master/.build/checkouts/Starscream-7041816469376470600/Source/Compression.swift:30:8: error: no such module 'CZLib'
    import CZLib
       ^
    /Users/mihael/Downloads/socket.io-client-swift-master/.build/checkouts/Starscream-7041816469376470600/Source/Compression.swift:30:8: error: no such module 'CZLib'
    import CZLib
       ^
    /Users/mihael/Downloads/socket.io-client-swift-master/.build/checkouts/Starscream-7041816469376470600/Source/Compression.swift:30:8: error: no such module 'CZLib'
    import CZLib
       ^
    <unknown>:0: error: build had 1 command failures
    error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/mihael/Downloads/socket.io-client-swift-master/.build/debug.yaml`

@nuclearace Could you please help?

**Comment by nuclearace** [comment]
I wonder why it's checking out 8.0.2, it should be checking out 8.0.3

**Comment by nuclearace** [comment]
I found the issue, it should be fixed in 11.1.1.

**Comment by MihaelIsaev** [comment]
@nuclearace Yeah it works in 11.1.1, thanks!
It would be great if you could fix it in swift4 branch as well.
